CREATE TABLE Todo (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  isCompleted BOOLEAN NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
